### ISSUE TITLE
Add support for clj-kondo

### ISSUE THREAD

**Issue by ieugen** [redplanetlabs/proxy-plus#14]
I imported this library in my ocde and while working on it from Calva I noticed it does not have support for clj-kondo.

To my knowledge, macro support needs to be added for this to work. 
Perhaps of help: 
https://github.com/clj-kondo/clj-kondo/blob/master/doc/config.md#unrecognized-macros

**Comment by nathanmarz** [comment]
This is something you can add to your own clj-kondo config. It doesn't need to be part of this project.

**Comment by ieugen** [comment]
Thanks for the feedback.
Wouldn't it be better (for reuse) to be part of this project?

**Comment by nathanmarz** [comment]
Yes, but it would also be something else we have to maintain.

**Comment by ieugen** [comment]
@nathanmarz :

It seems that `:lint-as` works pretty good at hiding nresolved symbol errors.

I used it like this (clj-kondo config as namespace metadata):
```
(ns dev.schema
  {:clj-kondo/config '{:lint-as {com.rpl.proxy-plus/proxy+ clojure.core/proxy}}}
```
