### ISSUE TITLE
Can't use classes generated from AOT

### ISSUE THREAD

**Issue by ericdallo** [redplanetlabs/proxy-plus#19]
Awesome project!

There is a issue though, only when the class was generated from AOT, when I try to use it I get a exception

```clojure
(ns foo)
(proxy+ Foo
        []
        java.util.Date
        (toString [_] "foo"))
```

```clojure
(.toString (com.github.clojure_lsp.intellij.extension.formatting.Foo.)) ;; throws exception only when class was generated from AOT
```

```
java.lang.NullPointerException: Cannot invoke "clojure.lang.IFn.invoke(Object)" because "this.toString13132" is null
 at foo.Foo.toString (:-1)
```

**Comment by ericdallo** [comment]
Any thoughts @nixin72?

**Comment by ericdallo** [comment]
Any thoughts @nathanmarz ?

**Comment by nathanmarz** [comment]
Do you get the exception if you use `Object` instead of `java.util.Date`?

**Comment by ericdallo** [comment]
Unfortunately, I get the same error @nathanmarz :/

This is the only thing blocking me from use proxy+, I need to custom name proxy AOT classes and point their name from xml

**Comment by nathanmarz** [comment]
Ah I see. Yea, you can't instantiate a class generated by `proxy+` yourself. That is, you should only be invoking methods on the object returned by `proxy+`.

**Comment by ericdallo** [comment]
I see, that's bad since I need to specify the class from a XML, I guess I will end up using gen-class for that, thank you anyway!
