### ISSUE TITLE
Dependencies not available on Maven central

### ISSUE THREAD

**Issue by camsaul** [redplanetlabs/proxy-plus#25]
This doesn't work with `deps.edn` if you just add the dependency as is:

```
Error building classpath. Could not find artifact com.rpl:rama-shaded-asm:jar:4.2 in central (https://repo1.maven.org/maven2/)
```

unless you add a `:mvn/repos` entry like 

```clj
{:mvn/repos {"rpl" {:url "https://nexus.redplanetlabs.com/repository/maven-public-releases"}}}
```

but this has downsides, since adding the extra maven repo has to be done for anything upstream that might be using something using this library. 

Any chance you can add the dependency to Clojars as well? If not, it's probably worth calling this out in the README so other people don't get tripped up on it

**Comment by nathanmarz** [comment]
Thanks, I updated the README.
