### ISSUE TITLE
Multiple constructors with the same arity can cause reflection

### ISSUE THREAD

**Issue by glchapman** [redplanetlabs/proxy-plus#4]
Here's a (silly) example:
```
user=> (import java.io.File)
java.io.File
user=> (defn mkfile [^String pathname] (proxy+ [pathname] File))
Reflection warning, NO_SOURCE_PATH:1:33 - call to user.proxy_plus6169 ctor can't be resolved.
#'user/mkfile
```
The problem only occurs when multiple constructors have the same arity. I think the problem goes away if you type hint (as java.util.Map) the function map which is passed when invoking the constructor.

**Comment by nathanmarz** [comment]
Thanks, fixed in 0.0.2.
